name: Prune Artifacts

on:
  schedule:
    - cron: '0 4 * * *' # daily at 04:00 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  prune:
    runs-on: ubuntu-latest
    env:
      RETENTION_DAYS: ${{ vars.ARTIFACT_RETENTION_DAYS || 14 }}
      RUN_RETENTION_DAYS: ${{ vars.WORKFLOW_RUN_RETENTION_DAYS || 30 }}
    steps:
      - name: Delete artifacts older than RETENTION_DAYS
        uses: actions/github-script@v7
        with:
          script: |
            const keepDays = parseInt(process.env.RETENTION_DAYS || '14', 10);
            const cutoff = Date.now() - keepDays*24*60*60*1000;
            let page=1;
            while(true){
              const { data } = await github.rest.actions.listArtifactsForRepo({ owner: context.repo.owner, repo: context.repo.repo, per_page: 100, page });
              if (!data.artifacts || data.artifacts.length === 0) break;
              for (const a of data.artifacts) {
                const created = new Date(a.created_at).getTime();
                if (!a.expired && created < cutoff) {
                  core.info(`Deleting artifact ${a.id} (${a.name}) from ${a.created_at}`);
                  await github.rest.actions.deleteArtifact({ owner: context.repo.owner, repo: context.repo.repo, artifact_id: a.id });
                }
              }
              if (!data.total_count || data.artifacts.length < 100) break;
              page++;
            }

      - name: Delete workflow runs older than RUN_RETENTION_DAYS
        uses: actions/github-script@v7
        with:
          script: |
            const keepDays = parseInt(process.env.RUN_RETENTION_DAYS || '30', 10);
            const cutoff = Date.now() - keepDays*24*60*60*1000;
            for await (const res of github.paginate.iterator(github.rest.actions.listWorkflowRunsForRepo, { owner: context.repo.owner, repo: context.repo.repo, per_page: 100 })) {
              for (const run of res.data) {
                if (new Date(run.created_at).getTime() < cutoff) {
                  core.info(`Deleting run ${run.id} from ${run.created_at}`);
                  await github.rest.actions.deleteWorkflowRun({ owner: context.repo.owner, repo: context.repo.repo, run_id: run.id });
                }
              }
            }
