name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-apc.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      # Configure upgrade banner defaults in released binaries at runtime.
      # The banner reads these at process start (not compile time).
      CODEX_AGENTIC_UPDATE_REPO: ${{ github.repository }}
      CODEX_AGENTIC_UPGRADE_CMD: bash <(curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/scripts/install.sh)
      CODEX_UPGRADE_URL: https://github.com/${{ github.repository }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            codex-acp -> target

      - name: Build (release)
        working-directory: codex-agentic
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        run: |
          rustc --version
          cargo build --release

      - name: Compute platform identifiers
        id: plat
        shell: bash
        run: |
          echo "arch=$(uname -m)" >> "$GITHUB_OUTPUT"
          echo "os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Package
        id: pkg
        shell: bash
        run: |
          set -euo pipefail
          VER="${GITHUB_REF_NAME}"
          RAW="${VER#v}"
          # Map pre-release cargo version (e.g., 0.39.0-apc.0) to a 4-part numeric for artifacts (0.39.0.0)
          ART="${RAW/-apc./.}"
          OS="${{ steps.plat.outputs.os }}"
          ARCH="${{ steps.plat.outputs.arch }}"
          NAME="codex-agentic-v${ART}-${OS}-${ARCH}"
          mkdir -p package dist
          cp codex-agentic/target/release/codex-agentic package/
          chmod +x package/codex-agentic
          cp LICENSE package/
          cp README.md package/README.md
          echo "See upstream codex for CLI docs; this binary delegates to upstream CLI by default. Use --acp for ACP mode." > package/README-agentic.md
          tar -C package -czf "dist/${NAME}.tar.gz" .
          echo "asset=dist/${NAME}.tar.gz" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-asset
          path: ${{ steps.pkg.outputs.asset }}
          if-no-files-found: error

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-asset'
          merge-multiple: true

      - name: Generate checksums
        run: sha256sum *.tar.gz > SHA256SUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            *.tar.gz
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
